pyswarms/utils/functions/single_obj.py

I have implemented beale_func(x) in a vectorized manner.  It passes the tests you have already created.

implemented beale

---

pyswarms/utils/functions/single_obj.py

I finished implementing all the functions.  I also looked at the handy PEP8 document you sent me and I took suggestions from it.
The only function that was tricky was levi_func(x).  If you have a better implementation suggestion I'd be happy to redo it or anything else you'd like me to improve.

implemented all single-objective functions

---

HISTORY.rst
paper/paper.md

Update History and Documentation

---

CONTRIBUTING.rst
README.rst
docs/index.rst
paper/paper.md

Update Statement of Need

---

paper/paper.bib
paper/paper.md

Reference:  openjournals/joss-reviews#433
Extends the previous version of the paper (very short) into
a longer and more explicit version. A short introduction for
PSO was added, some design principles, and a brief mention
to some use-cases.
Author: @ljvmiranda921
E-mail: ljvmiranda@gmail.com

Update paper.md (#70)

---

pyswarms/single/global_best.py
pyswarms/single/local_best.py

More elaborate tolerance on objective fucntion
evaluation termination criterion.

Improve the relative tolerance on objective feature

---

AUTHORS.rst
HISTORY.rst
README.rst
pyswarms/__init__.py
setup.cfg
setup.py

Prepare v0.1.9

---

examples/inverse_kinematics.ipynb

I have created an Inverse Kinematics Tutorial in a Jupyter Notebook for the issue #136

Created Inverse Kinematics tutorial

---

pyswarms/backend/topology/pyramid.py
pyswarms/backend/topology/star.py
tests/backend/topology/test_pyramid.py
tests/backend/topology/test_random.py
tests/backend/topology/test_ring.py
tests/backend/topology/test_star.py

Added a new test to the topology classes for the neighbor_idx attribute, checks if it is assigned. Changed the way the neighbor_idx attribute is assigned in the Star and Pyramid topology

Add test for the neighbor_idx attribute of topologies

---

AUTHORS.rst
README.md

Reference: #180 
- Put maintainers above and link to AUTHORS.rst instead. 
- Update author names

Update authors list

---

HISTORY.rst
pyswarms/__init__.py
setup.cfg
setup.py

Bump version and setup.py

---

HISTORY.rst
docs/features.rst

Added the GeneralOptimizer and the plotters module to the `features.rst`
file and provided a deprecation warning in the environment package.
Updated the `HISTORY.rst` file with the new release note format based on
the notes in #180.
Makes the `HISTORY.rst` file look prettier.

Update features.rst and HISTORY.rst

---

requirements_dev.txt

All dependency updates from pyup.io goes here

Update dependencies via pyup

---

.gitignore
README.md
Vagrantfile
provisioner.sh
requirements_dev.txt

- **NEW:** Collaboration tool using Vagrantfiles - #193. Thanks @jdbohrman!
- **NEW:** Add configuration file for pyup.io - #210
- **FIX:** Fix for documentation in ReadTheDocs being incomplete- #208 
- **IMPROVED:** Update dependencies via pyup - #204

Prepare Release v.0.3.1

---

pyswarms/backend/topology/base.py
pyswarms/base/base_discrete.py
pyswarms/base/base_single.py

Reference: #198 
There's really no big change aside from the ABC.
[More about Abstract Base Classes](https://pymotw.com/3/abc/)

Update base classes to inherit from ABC

---

requirements-dev.txt
requirements.in
requirements.txt

There was a security risk when installing the old version of numpy. This PR fixes that

Update numpy version

---

HISTORY.rst

Updated HISTORY.rst to match the release notes.
As outlined in #298 .

Updated HISTORY.rst

---

pyswarms/single/global_best.py

Minor documentation fix as described by title.
N/A

Simple documentation fix (global best velocity update equation, m -> w)

---

README.md

In README there were old names of properties and I updated them
- get_cost_history to cost_history
- get_pos_history to pos_history
- get_velocity_history to velocity_history
- get_mean_neighbor_history to mean_neighbor_history

Update README.md, updating methods' names

---

README.md

Updates the references from last year :)

Update references with new citations (#374)

---

docs/examples/usecases/train_neural_network.ipynb

Refactor code train_neural_network notebook

refactor notebook

---

README.md

Fix link from https://doi.org/joss.00433 to https://doi.org/10.21105/joss.00433 but the visual stay the same.
Fix link from https://doi.org/joss.00433 to https://doi.org/10.21105/joss.00433 but the visual stay the same.
```
[https://doi.org/joss.00433](https://doi.org/10.21105/joss.00433)
```
Fixing the link when clicked, but not chainging the visual to make it the same as in research gate.
Just click the link.
- [x ] Breaking change (fix or feature that would cause existing functionality to change)
- [] I have read the **CONTRIBUTING** document.
- [] I have added tests to cover my changes.

Fix link from https://doi.org/joss.00433 to https://doi.org/10.21105/joss.00433 but the visual stay the same

---

pyswarms/base/base_discrete.py
pyswarms/base/base_single.py
pyswarms/discrete/binary.py
pyswarms/single/general_optimizer.py
pyswarms/single/global_best.py
pyswarms/single/local_best.py
tests/optimizers/test_general_optimizer.py

Updated stopping criteria extending the `ftol` functionality.
Stop the optimization if the objective function value does not improve over `ftol_iter` iterations.
Enhancements:
- Added a `ftol_iter` parameter to BinaryPSO, GeneralPSO, LocalBestPSO and GlobalBestPSO.
- The tolerance `ftol` of the objective function must be consistent over the next `ftol_iter` iterations
- Initial functionality of `ftol` is maintained as the default value of `ftol_iter` is set to `1`
#373 
The are 3 different stopping criteria defined ( maxiter , minstep, minfunc), all of these are hard set values. The proposed enhancement is often used in metaheuristic optimization, where the `maxiter` cannot be pre determined. In these cases, the user can define the stopping criteria as 
> If the objective function value …

Stopping criteria: Tolerance in objective function over iterations

---

azure-pipelines.yml
requirements-dev.in
requirements-dev.txt

Modernize CI/CD Pipelines in Azure

---

pyswarms/utils/plotters/formatters.py
pyswarms/utils/plotters/plotters.py
tests/utils/plotters/test_plotters.py

With this pull request, multiprocessing is added for contour and surface plotting. The parameters are optional thus do not break any other code. Code was inspired by the multiprocessing implementation of the optimization itself.
Speeding up plotting on systems with a lot of CPU cores.
Manually tested, as it is a minor change.

added multiprocessing for contour and surface plotting

---

README.md

PySwarms is now available also as a rpm package. It can easily be installed using dnf package manager within Fedora OS.

Installation instructions for Fedora Linux distro users
