ljvmiranda921/pyswarms

- pyswarms/single/local_best.py
- pyswarms/utils/search/grid_search.py
- tests/utils/search/test_gridsearch.py
Hi LJ,
I put together a simple grid_search and test for the PSO parameter optimization. 
I'm thinking it might make sense to create a MockOptimizer() class to test the method directly, independent of the pyswarms optimizers, but wanted to get your thoughts on that before building it. 
Also, I'm not sure if it's confusing that I've required `objective_func` and `iters` to be set up front when creating the GridSearch instance, but I think this might be clearer than requiring them to be passed at the time of the optimize call. Let me know if you'd prefer the latter, and I can change that. 
Once we confirm this is on a good path, I can follow the same general approach to build the random_search, and then write up a Jupyter notebook showing them both in context. 
I look forward to hearing your …
> Add grid_search

- docs/features.rst
- pyswarms/utils/search/__init__.py
- pyswarms/utils/search/base_search.py
- pyswarms/utils/search/grid_search.py
- pyswarms/utils/search/random_search.py
- tests/utils/search/test_gridsearch.py
- tests/utils/search/test_randomsearch.py
This commit adds a SearchBase class for GridSearch and RandomSearch,
which defines an __init__ that sets all attributes for instances
as well as score and search methods.
This commit also adds RandomSearch, which provides search for optimal
performance on objective function over combinations of hyperparameter
values with specified bounds for specified number of combination
iterations.
Author: SioKCronin
Email: siobhankcronin@gmail.com
> Add BaseSearch and RandomSearch

- pyswarms/utils/search/base_search.py
- pyswarms/utils/search/grid_search.py
- pyswarms/utils/search/random_search.py
- tests/utils/search/test_randomsearch.py
… (#27)
Check name of optimizer member in SearchBase.
Check type of n_selection_iters member in RandomSearch.
Add self.assertions() line to __init__() in each of Searchbase, GridSearch, and RandomSearch.
Add call to super().assertions() in RandomSearch.
Author: jazcap53
Email: andrew.jarcho@gmail.com
> Implement assertions() in search #27

- .travis.yml
- setup.py
- tests/utils/environments/test_plot_environment.py
This pull request aims to install the ffmpeg in travis-ci. This
is to facilitate the success of checks that use the `matplotlib.animation.FuncAnimation`
class. The modifications are done in the `.travis.yml` file.
> Install ffmpeg to run animation tests

- tests/utils/search/test_gridsearch.py
- tests/utils/search/test_randomsearch.py
Tests that a bad type for the `optimizer` parameter to `GridSearch()` raises a `TypeError`.
Tests that a bad type for the `optimizer` parameter or the `n_selection_iters` parameter
to `RandomSearch()` raises a `TypeError`.
Author: jazcap53
Email: andrew.jarcho@gmail.com
> Test assertions in search (#27)

- pyswarms/utils/environments/plot_environment.py
- pyswarms/utils/functions/single_obj.py
Offset shape should be (N,2). The bug can be seen when using the Beale function (which had a typo for the global minimum).
> Fix offset shape for 2D animation

- pyswarms/base/base_single.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
- tests/optimizers/test_global_best.py
- tests/optimizers/test_local_best.py
Added two new features which are:
1. Provide the possibility for the user to set manually a starting point for both global and local PSO.
2. Provide the possibility for the user to specify manually a tolerance in the objective function evaluation.
These features are available for many optimization algorithms such as those used in the scipy optimize library. I think they are useful for instance when we want to compare PSO with Nelder-Mead (the version under scipy optimize), with those two attributes, we can set them on equal footing.
Note: Had to close my last PR because it does not pass the travis test, due to the test of tolerance feature. The behavior is normal since I am doing a simple test (in fact I am betting on Local PSO to finish before the maximum iteration which is not …
> Add guess and acceptable tolerance of objective function evaluation features

- pyswarms/utils/functions/single_obj.py
Resolve the issue of no matching shape between
the input and the output of the function.
> Fix the rosenbrock function

- pyswarms/backend/operators.py
- pyswarms/backend/topology/__init__.py
- pyswarms/backend/topology/base.py
- pyswarms/backend/topology/ring.py
- pyswarms/backend/topology/star.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
- tests/backend/test_operators.py
- tests/backend/topology/conftest.py
- tests/backend/topology/test_ring.py
- tests/backend/topology/test_star.py
The next few commits should fail, I don't have tests for it yet.
> Add Topologies

- pyswarms/backend/generators.py
This commit makes the if-else statements in generators more concise.
To be honest, I didn't know what came into my mind as to why I nested
those if statements. It turns out that using the "and" operator is
much, much better.
Signed-off-by: Lester James V. Miranda <ljvmiranda@gmail.com>
> Modify if-else statements in generators

- pyswarms/discrete/binary.py
Change sigmoid function from 1 / (1 + np.exp(x)) to 1 / (1 + np.exp(-x))
> error in the sigmoid function

- docs/api/pyswarms.single.rst
- docs/api/pyswarms.topology.rst
- pyswarms/__init__.py
- pyswarms/backend/topology/__init__.py
- pyswarms/backend/topology/pyramid.py
- pyswarms/single/__init__.py
- pyswarms/single/general_optimizer.py
- tests/optimizers/conftest.py
- tests/optimizers/test_general_optimizer.py
Created a `GeneralOptimizer` class for the implementation of new topologies. Updated the documentation and created a new test file for the new class. With the new test file, it became possible to test the `Pyramid` class (topology) more easily.
Fixed an index error that occurred in the `Pyramid` topology because of a type mismatch.
Resolves: #148
> Create GeneralOptimizer class and fix index error in Pyramid class

- requirements_dev.txt
The change caused build errors in ReadTheDocs. Turns out that
the new change (without changelog even) is not yet present in
the PyPI servers.
Signed-off-by: Lester James V. Miranda <ljvmiranda@gmail.com>
> Revert pyyaml version change from 3.12 to 4.1

- docs/api/pyswarms.topology.rst
- pyswarms/backend/topology/__init__.py
- pyswarms/backend/topology/pyramid.py
- pyswarms/backend/topology/random.py
- pyswarms/single/general_optimizer.py
- tests/backend/topology/conftest.py
- tests/backend/topology/test_random.py
- tests/optimizers/conftest.py
- tests/optimizers/test_general_optimizer.py
Added a new topology with random neighbours. Added documentation and
a test file for it and reworked the documentation of the
GeneralOptimizer class to incorporate all available topologies.
Simplified the fixture function for the GeneralOptimizer class.
Cited the relevant paper for the algorithm implemented.
I implemented the algorithm to compute the neighbours in a separate, private method inside the `Random` class because I thought it's cleaner that way. We need such a complicated algorithm because it's important that the "graph" we create when assigning neighbours is fully connected.
> Add Random topology class

- pyswarms/backend/topology/base.py
- pyswarms/backend/topology/pyramid.py
- pyswarms/backend/topology/random.py
- pyswarms/backend/topology/ring.py
- pyswarms/backend/topology/star.py
- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- pyswarms/single/local_best.py
- tests/backend/topology/conftest.py
- tests/backend/topology/test_pyramid.py
- tests/backend/topology/test_random.py
- tests/backend/topology/test_ring.py
- tests/optimizers/conftest.py
- tests/optimizers/test_general_optimizer.py
I added a new functionality to the topologies with which one can decide if the topology is static (i.e. the neighbours don't change over the course of the optimization) or dynamic (i.e. the neighbours change over the course of the optimization). This new functionality includes the addition of two new attributes to the topology classes that can be static or dynamic:
* `static`: a boolean that decides whether the topology is static or not
* `neighbor_idx`: a matrix with the neighbor indices for every particle.
To initialize a topology it is now necessary to set the `static` attribute like so:
```python
Pyramid(static=True)
```
The other functionalities remain unchanged.
I also changed the tests to have new parametrizations so it works without a lot of `pytest` marks. The documentation has …
> Add static/dynamic functionality for topologies

- pyswarms/utils/plotters/formatters.py
- pyswarms/utils/plotters/plotters.py
Bug fix: Added 'z-axis' to formatters/Designer attribute 'labels' to prevent index out of range error when plotting in 3D. Also added a third dimension to 'limits' for the same reason. 
New feature:  I added a colormaps property to the Designer class in formatters.py to allow the user to choose whichever one they want. It uses the same style as other properties of the class, and the module imports matplotlib.cm to validate both types of colormaps in matplotlib. I edited plotters/plot_countour to initialize a Designer object with a default colormap if none is provided. I've tested with every category of colormap as well as custom colormaps and verified that it is working as intended.
Default parameter change: Mesher.delta from 0.001 to 0.1. This makes it safe to run many of the functions …
> Fix plotter module (#167)

- pyswarms/utils/functions/single_obj.py
- tests/utils/functions/conftest.py
- tests/utils/functions/test_singleobj_bounds.py
- tests/utils/functions/test_singleobj_dims.py
- tests/utils/functions/test_singleobj_return.py
- tests/utils/functions/test_singleobj_returndims.py
Objective Function Updates: Verified Goldstein and Booth functions working and removed TODO tags. Fixed Bulkin No 6 and removed TODO tag. Implemented Cross-in-Tray, Easom, Eggholder, Himmelblau's, Holder Table, and Three Hump Camel functions. File is getting long so I sorted the functions and added a list of functions and their corresponding function name to the docstring.
Add more benchmark functions #158 
More is better, right? 
I created a notebook with all the added functions and tested each function as I implemented it. All functions function in the full domain and visually match examples found online, and the minimums are what they should be. 
Then I used flask8 and black. I restricted flask8 and black testing to the file that I edited. 
I also ran py.test.
> Add objective functions (#158)

- requirements_dev.txt
It turns out that pyup and pyyaml has anomalous versions and
has become buggy. We fix this dependency by having pyup ignore
such changes. PyYAML is only used for our logging configs, so
this will not be harmful.
Signed-off-by: Lester James V. Miranda <ljvmiranda@gmail.com>
> Fix pyyaml dependency

- pyswarms/backend/topology/pyramid.py
- pyswarms/backend/topology/star.py
- pyswarms/backend/topology/von_neumann.py
- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- tests/backend/topology/test_pyramid.py
- tests/backend/topology/test_random.py
- tests/backend/topology/test_ring.py
- tests/backend/topology/test_star.py
- tests/backend/topology/test_von_neumann.py
- tests/optimizers/conftest.py
- tests/optimizers/test_general_optimizer.py
I cleaned up the code for the release of v0.3.0. The changes I made include:
- Set the `Star` topology to static and only assign the `neighbor_idx` attribute if it is not already assigned.
- Added the `VonNeumann `topology to the `GeneralOptimizer `with the necessary changes to the documentation and new exceptions for missing attributes.
- Added the `VonNeumann `topology to the `GeneralOptimizer `tests. The exceptions are tested and the topology fixture now also uses the `VonNeumann `class. Cleaned up the tests and added a static parametrization.
- Fixed a bug in the `Pyramid `topology where the optimize function of the `GeneralOptimizer `would output a `ValueError `because for some particles the neighbours were not computed. See also: #183 
- Changed the boundary for the connectivity of …
> Clean up changes for v0.3.0

- README.md
This commit updates the header source from local to imgur.
Turns out that whenever we create a setup file, the docs
directory is excluded, thus, the header image is nowhere
to be found. By sourcing the images from imgur, we can
resolve this problem.
Signed-off-by: Lester James V. Miranda <ljvmiranda@gmail.com>
> Update image source in README

- pyswarms/utils/.pyup.yml
It seems that pyup is annoying. This commit fixes that. Instead of
spamming PRs everyday, it only creates relevant PRs per month. I've also
set the types of updates into "insecure." We will only update
dependencies that were found risky or vulnerable, no need to update
requirements whenever there is a new release.
> Add configuration file for pyup

- README.md
- docs/examples/basic_optimization.rst
- docs/examples/custom_optimization_loop.rst
- docs/examples/visualization.rst
- examples/basic_optimization.ipynb
- examples/custom_optimization_loop.ipynb
- examples/visualization.ipynb
- pyswarms/single/general_optimizer.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
- pyswarms/utils/functions/single_obj.py
- pyswarms/utils/plotters/formatters.py
- pyswarms/utils/plotters/plotters.py
- pyswarms/utils/search/grid_search.py
- pyswarms/utils/search/random_search.py
- tests/optimizers/conftest.py
- tests/optimizers/test_general_optimizer.py
- tests/optimizers/test_global_best.py
- tests/optimizers/test_local_best.py
- tests/optimizers/test_objective_func_with_kwargs.py
- tests/utils/functions/test_singleobj_bounds.py
- tests/utils/functions/test_singleobj_dims.py
- tests/utils/functions/test_singleobj_return.py
- tests/utils/functions/test_singleobj_returndims.py
- tests/utils/plotters/conftest.py
- tests/utils/search/conftest.py
Same as before, but this time checked out from `development` branch :smile: 
Issue #219 
Merging changes proved to be troublesome.
Same changes has been made, tests should work.
> Re: Removed '_func' from single obj function names

- examples/basic_optimization.ipynb
- examples/custom_optimization_loop.ipynb
- wherever the single_obj.sphere function is called, only `iter` argument is given, arguments `print_step` and `verbose` are removed.
If this checks out I will make similar changes to other notebooks. Since I am a first-timer I am just changing one file to make sure I am doing it right.
> Changes made to basic_optimization.ipynb notebook for new API

- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
The PR that added boundary/velocity handlers (#238) removed the fixes to duplicate function calls introduced in #266.
Resolves: #289 
Both features should exist at the same time 👍 
Ran tests locally
> Re-fix duplicate cost function calls in optimize()

- pyswarms/backend/handlers.py
- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
The memory of the `BoundaryHandler` in the Optimizers are now populated before the optimization loop starts. This prevents the Optimizers from generating positions that are out of the bounds in the first two iterations.
Also added newlines for the documentation of the "reflective" strategy because I forgot them.
Resolves #285 
See the issue.
Ran the test.
> Fix handlers

- pyswarms/discrete/binary.py
Resolves #292
The binary optimizer returns the entire final swarm instead of the final best position.
I think this happens because in the return stage of the optimize() function, we are copying self.swarm.best_pos which is an array (n_dimensions, particles), instead of the position of the best particle.
The expected behavior is implemented in local_best.py.
#292 
1. Ran tests locally
2. Example notebook (feature_selection)
3. Personal project 
See #292
> BinaryPSO should return final best position instead of final swarm

- pyswarms/base/base_discrete.py
- pyswarms/base/base_single.py
- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
Resolves #303
Removed non-feature "fast" flag from optimizers:
- Updated function definitions
- Updated docstrings
- Removed `time.sleep` usages
#303 
Discussed in #303.
All optimizers have an unnecessary optional argument `fast` whose default value makes the optimizers call `time.sleep` at the start of each iteration. 
This is a non-feature and was only introduced to try to make `tqdm` progress bars look nice 😄
A cool side-effect of this PR is that the tests run faster now since a lot of test cases use an optimizer with 1000 iterations (= 10 secs sleeping 💤).
Ran test suite locally
> Removed non-feature "fast" flag from optimizers

- pyswarms/backend/operators.py
- pyswarms/base/base_discrete.py
- pyswarms/base/base_single.py
- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
- pyswarms/utils/decorators/decorators.py
- tests/optimizers/abc_test_optimizer.py
- tests/optimizers/test_general_optimizer.py
The goal of this PR is to support parallel particle evaluation in PySwarms.
~~### **This is a draft PR to collect feedback on implementation specific decision regarding this feature.**~~
~~At the moment, I only updated the optimize() implementation to use the `compute_objective_function` abstraction, but the same changes can be applied easily to the remaining optimizers.~~
#258 
The main motivation for this PR is to improve the performance of PySwarms optimizers by parallelizing the evaluation of each particle during optimization.
This is especially relevant when: 
1. The objective function is expensive to compute.
2. The swarm has a high number of particles (thousands, millions, ...)
My proposal at the moment consists in abstracting the existing direct calls on the `objective_func` to a …
> Support parallel particle evaluation

- pyswarms/utils/search/base_search.py
Sorry, I used the wrong branch in [PR#324](https://github.com/ljvmiranda921/pyswarms/pull/324)，Please ignore it.
Fix:
when i use "RandomSearch" with parmameter "bounds", the class "SearchBase" method "generate_score" has a issue:
```
parmameter "self.vclamp" will be assign to parmameter "bh_strategy" in the "optimizer" ,
such as class "GlobalBestPSO",class "GeneralOptimizerPSO" and class "LocalBestPSO".
```
Should use python keyword argument to fix it 
use python keyword argument to change 
```python
self.n_particles, self.dims, options, self.bounds, self.vclamp
```
to 
```python
self.n_particles, self.dims, options, self.bounds, velocity_clamp=self.vclamp
```
Bug fix
```python
g = RandomSearch(GlobalBestPSO, n_particles=n_particles, dimensions=dimensions,
options=options, …
```
> fix parmameter doesnot match

- docs/examples/basic_optimization.rst
- docs/examples/inverse_kinematics.rst
- examples/basic_optimization.ipynb
- examples/inverse_kinematics.ipynb
Remove `verbose` and `print_step` arguments when calling `GlobalBestPSO` optimizer in multiple examples and docs. 
Fixing outdated examples and documents issues reported in [issue 264](https://github.com/ljvmiranda921/pyswarms/issues/264) and in [issue 317](https://github.com/ljvmiranda921/pyswarms/issues/317).
Thank you for providing great open source project.
Was trying to run inverse kinematics example and basic optimization example jupyter notebook. Original examples complain `unexpected keyword argument` errors for `verbose` and `print_step`. 
I haven't gone through the solver source code, hopefully this is the right fix that is inline with author's intention. 
Ran basic_optimization jupyter notebook locally.
> Fix basic optimization example unknown arguments issues

- MANIFEST.in
- setup.py
- tox.ini
Instead of using requirements.txt for installing via `pip` or `python setup.py install`, we are now just using a more relaxed `requirements.in`
There were some issues regarding the use of `requirements.txt` that causes some conflict with other installed packages when pyswarms is installed system-wide. By unpinning some dependencies in our library, we can remove such.
For pyswarms, there's really no hard requirement to depend upon numpy, scipy, etc.
#323
> Relax dependencies when installing via setup.py

- requirements.txt
Don't know why it was removed after #300, but it's still missing from PyPI and the master branch. Please feel free to comment on the version (or anything).
#300 provides the background.
Thanks.
> Added pyyaml in requirements.txt

- pyswarms/backend/handlers.py
- pyswarms/utils/reporter/reporter.py
- pyswarms/utils/search/base_search.py
This resolves a rendering issue with [handlers](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.handlers.html) (see, for example, [here](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.handlers.html#pyswarms.backend.handlers.BoundaryHandler.nearest)), as well as minor docstring issues producing warnings during documentation rebuild.
> Minor fixes

- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
The verbose switch was added to optimize() method. In addition, the pool of processes was closed at the end of calculations.
The pool of processes was not being closed at the end of calculations. It is being closed now.
The verbose (=True or False) is added to optimize() method to turn on or off the logging and progress bar.
> Adding verbose switch and fixing unclosed pool

- docs/examples/usecases/electric_circuit_problem.ipynb
- pyswarms/backend/handlers.py
Fixed some math that was badly rendered in the documentation and examples.
#389
We want the documentation to stay up to date and clean.
> Fix unrendered math

- docs/examples/tutorials/tolerance.ipynb
- pyswarms/base/base_discrete.py
- pyswarms/base/base_single.py
- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
- tests/optimizers/test_tolerance.py
Solves a number of recent cases regarding `ftol`, `ftol_iter`, their implementation, testing and usage.
makes sure `ftol_iter >= 0` and `int`
`append()` and `popleft()` methods integrated
improve unit test coverage by adding test for `assertion`, effects on optimizer without `ftol`, with `ftol` and with both `ftol` and `ftol_iter` based on 0-1 knapsack problem.
#397 #373  
Improves documentation, covers testing of tolerance based parameters and improves understanding of the effects of tolerance parameters.
Additional testing script for all tolerance related parameters.
> Tolerance parameters

- pyswarms/discrete/binary.py
- pyswarms/single/general_optimizer.py
- pyswarms/single/global_best.py
- pyswarms/single/local_best.py
- tests/optimizers/test_verbose.py
Fix verbose behavior.
Toggled verbose options.
- `verbose=False` silent mode
- `verbose=True` display status bar.
#406 
Added new test for verbose behavior. Silent mode shows no output. `verbose = True` shows status bar.
> Fix verbose behavior

- pyswarms/discrete/binary.py
Since `m` wasn't defined anywhere, I assumed the inertia `w` was actually meant here, similar to the formula for the real-valued algorithm. In addition to that, the `w` key was also missing in documentation for the options dict keyword argument in the initialization of `BinaryPSO`, fixed that as well.
I guess #389 ?
This change improves the clarity of the documentation.
Not applicable.
Not applicable.
> Fix doc typos in binary discrete optimizer module (pyswarms.discrete.binary)

- requirements.in
This gives information to package managers like pip that PyYAML is a required dependency.
#420
Fixes #420 
I believe no testing is required here.
> Add pyyaml to requirements.in

- docs/examples/usecases/train_neural_network.ipynb
There is a typo on train_neural_network.ipynb, this PR fix that typo.
Solves Issue #428 
In cell 5 is defined logits_function, but in cells 6 and 9 is written logits_funciton. This pull request fix the typo.
> Fix typo on train_neural_network.ipynb

- docs/conf.py
pyswarms documentation fails to build with the newest Sphinx stack.
Report: https://download.copr.fedorainfracloud.org/results/ksurma/pygments-2.9.0/fedora-rawhide-x86_64/02258998-python-pyswarms/build.log.gz
Problem:: Changed in version 1.8: add_stylesheet() was renamed to add_css_file() [See API documentation](https://www.sphinx-doc.org/en/master/extdev/appapi.html)
> add_stylesheet -> add_css_file

- requirements-dev.txt
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>
Docs aren't built successfully by Read The Docs because Sphinx is pinned to v1.7.6 in `requirements-dev.txt`, but https://github.com/ljvmiranda921/pyswarms/pull/468 introduced a doc change which requires Sphinx v1.8 or newer. This PR updates the Sphinx version to `>=1.8,<2` in `requirements-dev.txt` so that the docs can hopefully be built successfully.
No open issues address that the docs fail, but this issue e.g. #389 cannot go on unless this is fixed.
We depend on PySwarms in PyEBSDIndex (https://github.com/USNavalResearchLaboratory/PyEBSDIndex) and would like for our dependencies to have an up-to-date documentation for our users to read.
On Ubuntu 22.04.
Not tested, since I tried building the docs myself but got this error:
```bash
$ …
```
> Specify Sphinx version >=1.8,<2 in dev dependencies

- tests/utils/plotters/test_plotters.py
`SubplotBase` is available in `matplotlib.axes`; there's no need to use the private path.
Fixes #508 
Ran tests with Matplotlib 3.7 and 3.6.3.
> Fix tests with Matplotlib 3.7
